# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20191118_0456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Editor',
        ),
    ]
