# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_newsletterrecipients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Your bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
