# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_auto_20191120_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['user_name'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='editor',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
