# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_auto_20191120_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={},
        ),
    ]
