# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Your bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='tags',
        ),
    ]
